# main.yaml

openapi: 3.0.0
info:
  title: Discord Bot API
  version: 1.0.0
  description: Documentação de uma API simples para gerenciar o bot.
servers:
  - url: http://localhost:3000/api
    description: Servidor de Desenvolvimento
tags:
  - name: Bot
    description: Endpoints para gerenciar a operação do bot.
paths:
  $ref: './bot/bot.yaml'
